-- =============================================================================
-- OLÍMPICA RETAIL — ESQUEMA RELACIONAL PARA SUPABASE (PostgreSQL)
-- Script DDL: olimpica_tickets + olimpica_detalle_ticket
-- =============================================================================
-- Prerrequisito: La tabla `clientes` del script bancario debe existir primero.
-- Relación clave: olimpica_tickets.id_cliente → clientes.id_cliente
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLA A: olimpica_tickets  (Cabecera / Encabezado del tiquete de compra)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS olimpica_tickets (
    id_ticket           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relación con el cliente del banco
    id_cliente          BIGINT          NOT NULL
                            REFERENCES clientes (id_cliente) ON DELETE CASCADE,

    -- Temporalidad
    fecha_compra        TIMESTAMPTZ     NOT NULL,
    dia_semana          VARCHAR(12)     NOT NULL
                            CHECK (dia_semana IN (
                                'Lunes','Martes','Miércoles','Jueves',
                                'Viernes','Sábado','Domingo'
                            )),

    -- Tienda
    tienda_nombre       VARCHAR(80)     NOT NULL,
    tienda_ciudad       VARCHAR(60),

    -- Valor y pago
    monto_total         NUMERIC(15,2)   NOT NULL CHECK (monto_total > 0),
    medio_pago          VARCHAR(30)     NOT NULL
                            CHECK (medio_pago IN (
                                'Tarjeta_Credito_Banco',
                                'Tarjeta_Debito_Banco',
                                'Efectivo',
                                'Otras_Tarjetas'
                            )),

    -- Flags de contexto analítico (útiles para el agente de IA)
    es_dia_promocion    BOOLEAN         NOT NULL DEFAULT FALSE,  -- Martes, Miércoles de plaza, etc.
    es_quincena         BOOLEAN         NOT NULL DEFAULT FALSE,  -- días 14-16 y 29-31
    es_fin_de_semana    BOOLEAN         NOT NULL DEFAULT FALSE,
    contiene_tecnologia BOOLEAN         NOT NULL DEFAULT FALSE,  -- flag para detectar upgrade

    -- Segmento del cliente (desnormalizado para performance analítica)
    segmento_arquetipo  VARCHAR(30),
    es_ingreso_creciente BOOLEAN        NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Índices optimizados para queries del agente de IA
CREATE INDEX idx_tickets_cliente        ON olimpica_tickets (id_cliente);
CREATE INDEX idx_tickets_fecha          ON olimpica_tickets (fecha_compra);
CREATE INDEX idx_tickets_anio_mes       ON olimpica_tickets (DATE_TRUNC('month', fecha_compra));
CREATE INDEX idx_tickets_segmento       ON olimpica_tickets (segmento_arquetipo);
CREATE INDEX idx_tickets_medio_pago     ON olimpica_tickets (medio_pago);
CREATE INDEX idx_tickets_tecnologia     ON olimpica_tickets (contiene_tecnologia)
                                        WHERE contiene_tecnologia = TRUE;
CREATE INDEX idx_tickets_ingreso_crec   ON olimpica_tickets (es_ingreso_creciente)
                                        WHERE es_ingreso_creciente = TRUE;

-- Índice compuesto: muy usado en análisis de comportamiento por cliente y tiempo
CREATE INDEX idx_tickets_cliente_fecha  ON olimpica_tickets (id_cliente, fecha_compra DESC);

COMMENT ON TABLE olimpica_tickets IS
'Cabecera de tiquetes de compra en tiendas Olímpica. Vinculada a clientes del banco Serfinanza. Incluye flags de contexto para el agente de IA (tecnología, quincena, promoción).';

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLA B: olimpica_detalle_ticket  (Líneas de producto dentro del tiquete)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS olimpica_detalle_ticket (
    id_detalle          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relación con el tiquete padre
    id_ticket           BIGINT          NOT NULL
                            REFERENCES olimpica_tickets (id_ticket) ON DELETE CASCADE,

    -- Clasificación del producto
    seccion             VARCHAR(30)     NOT NULL
                            CHECK (seccion IN (
                                'Fruver',
                                'Carnes y Pescados',
                                'Lácteos y Huevos',
                                'Despensa',
                                'Aseo del Hogar',
                                'Cuidado Personal',
                                'Droguería',
                                'Tecnología',
                                'Electrodomésticos',
                                'Licores',
                                'Panadería y Repostería',
                                'Delicatessen'
                            )),

    producto_descripcion VARCHAR(120)   NOT NULL,
    cantidad            SMALLINT        NOT NULL CHECK (cantidad >= 1),
    precio_unitario     NUMERIC(15,2)   NOT NULL CHECK (precio_unitario > 0),
    subtotal            NUMERIC(15,2)   NOT NULL
                            GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,

    -- Marca propia Olímpica (relevante para perfil endeudado/ahorrador)
    es_marca_propia     BOOLEAN         NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Índices para análisis de categorías y productos
CREATE INDEX idx_detalle_ticket         ON olimpica_detalle_ticket (id_ticket);
CREATE INDEX idx_detalle_seccion        ON olimpica_detalle_ticket (seccion);
CREATE INDEX idx_detalle_marca_propia   ON olimpica_detalle_ticket (es_marca_propia)
                                        WHERE es_marca_propia = TRUE;

COMMENT ON TABLE olimpica_detalle_ticket IS
'Líneas de producto por tiquete Olímpica. La columna subtotal es calculada (cantidad × precio_unitario). Contiene flag de marca propia para análisis de sensibilidad al precio.';

-- ─────────────────────────────────────────────────────────────────────────────
-- VISTA ANALÍTICA: resumen de comportamiento retail por cliente
-- (Muy útil para el agente de IA al momento de evaluar ofertas)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW v_comportamiento_olimpica AS
SELECT
    t.id_cliente,
    t.segmento_arquetipo,
    t.es_ingreso_creciente,
    COUNT(DISTINCT t.id_ticket)                                     AS total_visitas,
    ROUND(AVG(t.monto_total)::NUMERIC, 2)                          AS ticket_promedio,
    MAX(t.monto_total)                                              AS ticket_maximo,
    SUM(t.monto_total)                                             AS gasto_total,
    SUM(CASE WHEN t.contiene_tecnologia THEN 1 ELSE 0 END)         AS visitas_con_tecnologia,
    SUM(CASE WHEN t.es_quincena THEN 1 ELSE 0 END)                 AS visitas_quincena,
    SUM(CASE WHEN t.es_dia_promocion THEN 1 ELSE 0 END)            AS visitas_dia_promo,
    MAX(t.fecha_compra)                                            AS ultima_visita,
    -- Distribución por medio de pago
    SUM(CASE WHEN t.medio_pago = 'Tarjeta_Credito_Banco'  THEN t.monto_total ELSE 0 END) AS monto_tc_banco,
    SUM(CASE WHEN t.medio_pago = 'Tarjeta_Debito_Banco'   THEN t.monto_total ELSE 0 END) AS monto_td_banco,
    SUM(CASE WHEN t.medio_pago = 'Efectivo'               THEN t.monto_total ELSE 0 END) AS monto_efectivo
FROM olimpica_tickets t
GROUP BY t.id_cliente, t.segmento_arquetipo, t.es_ingreso_creciente;

COMMENT ON VIEW v_comportamiento_olimpica IS
'Vista de comportamiento retail agregado por cliente. Diseñada para el agente de IA de ofertas y upgrades.';

-- ─────────────────────────────────────────────────────────────────────────────
-- VISTA ANALÍTICA: clientes candidatos a upgrade (señal clave para el agente)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW v_candidatos_upgrade AS
SELECT
    t.id_cliente,
    t.segmento_arquetipo,
    COUNT(DISTINCT t.id_ticket)                                    AS total_visitas_3m,
    SUM(t.monto_total)                                            AS gasto_3m,
    SUM(CASE WHEN t.contiene_tecnologia THEN t.monto_total ELSE 0 END) AS gasto_tecnologia_3m,
    MAX(t.monto_total)                                            AS ticket_max_3m,
    t.es_ingreso_creciente
FROM olimpica_tickets t
WHERE t.fecha_compra >= NOW() - INTERVAL '90 days'
GROUP BY t.id_cliente, t.segmento_arquetipo, t.es_ingreso_creciente
HAVING
    -- Señal 1: gasto en tecnología (el trigger más fuerte)
    SUM(CASE WHEN t.contiene_tecnologia THEN t.monto_total ELSE 0 END) > 0
    OR
    -- Señal 2: ticket promedio muy por encima de su segmento
    AVG(t.monto_total) > 300000;

COMMENT ON VIEW v_candidatos_upgrade IS
'Clientes con señales de upgrade detectadas en los últimos 90 días: compras en Tecnología o ticket promedio elevado. Input directo para el agente de IA de ofertas.';

-- =============================================================================
-- FIN DEL SCRIPT DDL RETAIL
-- Ejecutar DESPUÉS del DDL bancario (01_serfinanza_ddl_supabase.sql)
-- =============================================================================
