CREATE TABLE IF NOT EXISTS public.clientes (
    id_cliente BIGINT PRIMARY KEY,
    tipo_identificacion VARCHAR(10),
    numero_identificacion VARCHAR(50),
    fecha_expedicion_id DATE,
    id_requiere_correccion BOOLEAN,
    primer_nombre VARCHAR(100),
    segundo_nombre VARCHAR(100),
    primer_apellido VARCHAR(100),
    segundo_apellido VARCHAR(100),
    fecha_nacimiento DATE,
    genero VARCHAR(10),
    estado_civil VARCHAR(50),
    telefono_celular VARCHAR(20),
    telefono_fijo VARCHAR(20),
    email VARCHAR(150),
    direccion_residencia TEXT,
    ciudad_residencia VARCHAR(100),
    departamento VARCHAR(100),
    empresa VARCHAR(150),
    cargo VARCHAR(100),
    tipo_vinculacion VARCHAR(50),
    antiguedad_laboral_meses INTEGER,
    ingresos_iniciales NUMERIC(15,2),
    ingresos_actuales NUMERIC(15,2),
    egresos_mensuales NUMERIC(15,2),
    activos_totales NUMERIC(15,2),
    pasivos_totales NUMERIC(15,2),
    segmento_arquetipo VARCHAR(50),
    es_ingreso_creciente BOOLEAN,
    es_heavy_user_olimpico BOOLEAN,
    es_pep BOOLEAN,
    fecha_vinculacion_pep DATE,
    alerta_pep VARCHAR(100),
    fecha_ultima_actualizacion_datos DATE,
    canal_ultima_actualizacion VARCHAR(50),
    fecha_vinculacion_banco DATE,
    estado_cliente VARCHAR(50),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.productos (
    id_producto BIGINT PRIMARY KEY,
    id_cliente BIGINT REFERENCES public.clientes(id_cliente),
    tipo_producto VARCHAR(50),
    subtipo VARCHAR(50),
    fecha_apertura DATE,
    fecha_cierre DATE,
    cupo_o_monto_inicial NUMERIC(15,2),
    saldo_actual NUMERIC(15,2),
    estado VARCHAR(50),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.transacciones (
    id_transaccion BIGINT PRIMARY KEY,
    id_producto BIGINT REFERENCES public.productos(id_producto),
    id_cliente BIGINT REFERENCES public.clientes(id_cliente),
    fecha_transaccion DATE,
    hora_transaccion TIME,
    monto NUMERIC(15,2),
    moneda VARCHAR(10),
    tipo_movimiento VARCHAR(50),
    comercio_descripcion VARCHAR(150),
    categoria_comercio VARCHAR(100),
    canal_transaccion VARCHAR(50),
    es_quincena BOOLEAN,
    es_olimpico BOOLEAN,
    created_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.tarjetas_detalle (
    id_detalle BIGINT PRIMARY KEY,
    id_producto BIGINT REFERENCES public.productos(id_producto),
    modalidad VARCHAR(50),
    tasa_ea NUMERIC(5,2),
    cuota_manejo_mensual NUMERIC(15,2),
    cupo_total NUMERIC(15,2),
    saldo_utilizado NUMERIC(15,2),
    cupo_disponible NUMERIC(15,2),
    porcentaje_utilizacion NUMERIC(5,2),
    fecha_corte INTEGER,
    fecha_limite_pago DATE,
    pago_minimo NUMERIC(15,2),
    pago_total NUMERIC(15,2),
    puntos_acumulados INTEGER,
    tiene_pago_automatico BOOLEAN,
    upgrade_solicitado BOOLEAN,
    fecha_upgrade DATE,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.cdt_detalle (
    id_detalle BIGINT PRIMARY KEY,
    id_producto BIGINT REFERENCES public.productos(id_producto),
    monto_invertido NUMERIC(15,2),
    plazo_dias INTEGER,
    tramo_monto VARCHAR(50),
    tasa_ea_aplicada NUMERIC(5,2),
    interes_bruto_estimado NUMERIC(15,2),
    retencion_fuente NUMERIC(15,2),
    interes_neto_estimado NUMERIC(15,2),
    valor_total_vencimiento NUMERIC(15,2),
    modalidad_pago_interes VARCHAR(50),
    renovacion_automatica BOOLEAN,
    tipo_renovacion VARCHAR(50),
    fecha_constitucion DATE,
    fecha_vencimiento DATE,
    fecha_renovacion DATE,
    estado_cdt VARCHAR(50),
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.log_documentos (
    id_log BIGINT PRIMARY KEY,
    id_cliente BIGINT REFERENCES public.clientes(id_cliente),
    id_producto BIGINT REFERENCES public.productos(id_producto),
    tipo_documento VARCHAR(50),
    periodo_inicio DATE,
    periodo_fin DATE,
    fecha_emision TIMESTAMPTZ,
    origen_solicitud VARCHAR(50),
    estado_documento VARCHAR(50),
    created_at TIMESTAMPTZ
);
